# Generated by Django 4.0.2 on 2024-02-21 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exicuters',
            name='fio',
            field=models.CharField(blank=True, max_length=128, verbose_name='ФИО исполнителя'),
        ),
        migrations.AlterField(
            model_name='reestr_oferts',
            name='exicutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engine.exicuters', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='reestr_oferts',
            name='fio',
            field=models.CharField(max_length=128, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='reestr_oferts',
            name='number_orders_vozm',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Номер договора возм.'),
        ),
        migrations.CreateModel(
            name='Filials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Филиал')),
                ('fio_exicutor_filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engine.exicuters', verbose_name='ФИО сотрудников привязанных к филиалу')),
            ],
        ),
    ]
