# Generated by Django 4.1 on 2024-02-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_alter_exicuters_fio_alter_reestr_oferts_exicutor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reestr_oferts',
            name='comment',
            field=models.CharField(max_length=512, verbose_name='Комментарий'),
        ),
    ]
