# Generated by Django 4.1 on 2024-02-25 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_alter_reestr_oferts_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filials',
            name='fio_exicutor_filial',
        ),
    ]
