# Generated by Django 5.0.2 on 2024-03-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_location_alter_reestr_oferts_comment_contract_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_data',
            name='identification_document',
            field=models.CharField(blank=True, max_length=256, verbose_name='Индификационный документ'),
        ),
    ]
