# Generated by Django 4.1 on 2024-02-25 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_alter_exicuters_filial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exicuters',
            name='filial',
            field=models.ForeignKey(default='Тест', on_delete=django.db.models.deletion.PROTECT, to='engine.filials', verbose_name='Филиал к котрому привязан исполнитель'),
        ),
    ]
