# Generated by Django 4.1 on 2024-02-25 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_alter_exicuters_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reestr_oferts',
            name='filial',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.PROTECT, to='engine.filials', verbose_name='Филиал'),
        ),
    ]
