# Generated by Django 4.1 on 2024-02-25 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_reestr_oferts_filial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reestr_oferts',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engine.filials', verbose_name='Филиал'),
        ),
    ]
