# Generated by Django 4.0.2 on 2024-03-13 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_contract_data_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract_data',
            name='document_file',
        ),
    ]
