# Generated by Django 4.0.2 on 2024-03-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0012_alter_reestr_oferts_number_orders_vozm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_data',
            name='document_issue_date',
            field=models.DateField(blank=True, verbose_name='Дата выдачи документа'),
        ),
    ]
