# Generated by Django 5.0.2 on 2024-03-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0013_alter_contract_data_document_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exicuters',
            name='gender',
            field=models.CharField(choices=[('masc', 'Мужской'), ('femn', 'Женский')], default='femn', max_length=4),
        ),
    ]
